# Write your MySQL query statement below
SELECT D.NAME AS DEPARTMENT, E.NAME AS EMPLOYEE, E.SALARY FROM EMPLOYEE E JOIN DEPARTMENT D ON E.DEPARTMENTID = D.ID
JOIN (SELECT MAX(SALARY) AS SALARY,DEPARTMENTID FROM EMPLOYEE GROUP BY DEPARTMENTID) E1 ON E1.SALARY = E.SALARY 
AND E1.DEPARTMENTID = E.DEPARTMENTID